server:
    baseUrl: http://localhost
    port: 8082
    compression.enabled: true
    compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
    error:
        whitelabel:
            enabled: false

spring.jackson.default-property-inclusion: NON_NULL
spring.jackson.deserialization.fail-on-unknown-properties: false

actuator:
    password: test
    username: test
client:
    password: password
    username: clientId
#spring:
#    datasource:
#        password: root
#        platform: org.hibernate.dialect.MySQL5Dialect
#        url: jdbc:mysql://localhost:3306/quartz_demo_db
#        username: root
#    jpa:
#        hibernate:
#            ddl-auto: update
#            naming:
#                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#        properties:
#            hibernate.enable_lazy_load_no_trans: true
#        open-in-view: false
#        show-sql: true

json:
    errormsg: #Sorry, something went wrong. Please try again later
    diagnosticsDisabled: false

core.authorization.jwks.url: http://localhost:8081/.well-known/jwks.json